### PR TITLE
Center-On-Face Transformation

### PR DESCRIPTION
**Pull request by brady-aiello**
Added a transformation for centering the image on the most prominent face, with configurable zoom.

1. Use MLKit to find the most prominent face.
2. Find the largest and smallest squares that can contain the face, while trying to center horizontally, vertically, and both if possible.
3. Use the zoom level as a percentage of the the side length between the smallest and largest squares.

Added a No-Op Transformation as well, which makes comparisons on the sample app a little easier. It could also be used for benchmarking. Images attached.
no-op-and-zero
20-and-40
60-and-80
80-and-100

### CODE REVIEW

**Comment by brady-aiello** [comment]
I'll put up another with the ktlint fixes.

**Comment by brady-aiello** [comment]
Alright, that should do. Would love to hear your thoughts.

**Comment by Jawnnypoo** [comment]
Awesome stuff! I think that my feedback would be that we would create a new module for this, similar to what we do for `transformations-gpu`, since otherwise we would be forcing a hard dependency on the ML Kit even for those who are not using this transformation at all. I would love to see a new module, `transformations-face-detection` that contains this transformation and the dependency.

**Comment by brady-aiello** [comment]
Sweet! I'll do that. 😄

**Comment by brady-aiello** [comment]
Done. I've never contributed to OSS let alone had a maven module. This is wild. 😄

**Review by Jawnnypoo — APPROVED** [review]
Great contribution! Thanks so much!

**Comment by brady-aiello** [comment]
Yay! Thank YOU! 😄

**Pull request merged**
